## Extract

In [1]:
# import des fonctions d'extraction et transformation
import importlib
import sys
if 'etl.config' in sys.modules:
    # Supprimer les modules de la mémoire pour forcer le rechargement
    del sys.modules['etl.config'] 
if 'etl.transform' in sys.modules:
    del sys.modules['etl.transform']
if 'etl.extract' in sys.modules:
    del sys.modules['etl.extract']
    
from etl.extract import extract_charges_telephoniques, extract_charges_impression
from etl.transform import transform_charges_telephoniques, transform_charges_impression
from etl.config import persist_clean_tables

In [2]:
# Extraction + Transformation des données en une seule étape
ChargesTelephoniques = extract_charges_telephoniques()
ChargesImpression = extract_charges_impression()
ChargesTelephoniques = transform_charges_telephoniques(ChargesTelephoniques)
ChargesImpression = transform_charges_impression(ChargesImpression)

print(f"ChargesTelephoniques : {ChargesTelephoniques.shape}")
print(f"ChargesImpression   : {ChargesImpression.shape}")

[INFO] Validation dates ChargesTelephoniques - colonne 'DateOperation'...
  ✓ Toutes les dates valides (4945 lignes)
[INFO] Normalisation CodeEmployee (format: YAZ+nombre ou INCONNU)...
  ✓ CodeEmployee reformatés
[INFO] Normalisation NomDepartement - propagation inter-mois (valeur la plus récente)...
  ✓ Tous les départements valides
[INFO] Propagation NomRole et NumeroTelephone inter-mois (valeur la plus récente)...
  ✓ Tous les NomRole propagés
  ✓ Tous les NumeroTelephone propagés
[INFO] Imputation NomRole par ForfaitTND...
  Lignes avec NomRole manquant ou 'INCONNU' : 0
[INFO] Suppression doublons ChargesTelephoniques...
  ✓ Aucun doublon détecté
[INFO] Validation dates ChargesImpression - colonne 'DateImpression'...
  ✓ Toutes les dates valides (9945 lignes)
[INFO] Normalisation NomDepartement (ChargesImpression)...
  ✓ Tous les départements valides
[INFO] Validation TypeImpression...
  ✓ Tous les types impression valides
[INFO] Extraction CouleurImpression et FormatPapier...
  ✓ Extraction complète
[INFO] Correction CoutUnitaire...
  ✓ CoutUnitaire corrigés
[INFO] Correction NbPages...
  ✓ NbPages corrigés
ChargesTelephoniques : (4945, 9)
ChargesImpression   : (9945, 9)

In [3]:
# Affichage des premières lignes du DataFrame ChargesTelephoniques
ChargesTelephoniques.head()

,TelephoniqueID,NomDepartement,CodeDepartement,DateOperation,NomRole,CodeRole,CodeEmployee,NumeroTelephone,ForfaitTND
0,292260,ACHAT,ACH,2023-01-31,TECHNICIEN,TECH,YAZ054,90941122,25
1,292326,OLS,OLS,2023-01-31,SPECIALISTE,SP,YAZ116,50869708,40
2,292457,EHS,EHS,2026-05-31,TECHNICIEN,TECH,YAZ035,50859900,25
3,292589,TD,TD,2023-03-31,TECHNICIEN,TECH,YAZ096,90767788,25
4,292656,FINANCE,FIN,2023-04-30,TECHNICIEN,TECH,YAZ032,50526677,25

In [4]:
# affichages des premières lignes du DataFrame ChargesImpression
ChargesImpression.head()

,ImpressionID,NomDepartement,CodeDepartement,DateImpression,TypeImpression,NbPages,CoutUnitaire,FormatPapier,CouleurImpression
0,1,ACHAT,ACH,2023-03-03,A4-NB,459,0.026,A4,NOIR ET BLANC
1,2,ACHAT,ACH,2023-03-15,A4-COULEUR,406,0.156,A4,COULEUR
2,3,ACHAT,ACH,2023-03-17,A4-NB,38,0.026,A4,NOIR ET BLANC
3,4,ACHAT,ACH,2023-03-19,A4-NB,85,0.026,A4,NOIR ET BLANC
4,5,ACHAT,ACH,2023-03-20,A3-NB,232,0.052,A3,NOIR ET BLANC

## Transform

In [5]:
# Affichage des données transformées - ChargesTelephoniques

In [6]:
print(f"ChargesTelephoniques apres transformation : {ChargesTelephoniques.shape}")
ChargesTelephoniques.head()

ChargesTelephoniques apres transformation : (4945, 9)

,TelephoniqueID,NomDepartement,CodeDepartement,DateOperation,NomRole,CodeRole,CodeEmployee,NumeroTelephone,ForfaitTND
0,292260,ACHAT,ACH,2023-01-31,TECHNICIEN,TECH,YAZ054,90941122,25
1,292326,OLS,OLS,2023-01-31,SPECIALISTE,SP,YAZ116,50869708,40
2,292457,EHS,EHS,2026-05-31,TECHNICIEN,TECH,YAZ035,50859900,25
3,292589,TD,TD,2023-03-31,TECHNICIEN,TECH,YAZ096,90767788,25
4,292656,FINANCE,FIN,2023-04-30,TECHNICIEN,TECH,YAZ032,50526677,25

In [7]:
print(f"ChargesImpression apres transformation : {ChargesImpression.shape}")
ChargesImpression.head()

ChargesImpression apres transformation : (9945, 9)

,ImpressionID,NomDepartement,CodeDepartement,DateImpression,TypeImpression,NbPages,CoutUnitaire,FormatPapier,CouleurImpression
0,1,ACHAT,ACH,2023-03-03,A4-NB,459,0.026,A4,NOIR ET BLANC
1,2,ACHAT,ACH,2023-03-15,A4-COULEUR,406,0.156,A4,COULEUR
2,3,ACHAT,ACH,2023-03-17,A4-NB,38,0.026,A4,NOIR ET BLANC
3,4,ACHAT,ACH,2023-03-19,A4-NB,85,0.026,A4,NOIR ET BLANC
4,5,ACHAT,ACH,2023-03-20,A3-NB,232,0.052,A3,NOIR ET BLANC

## Stockage SQL Server

In [8]:
from etl.config import persist_clean_tables

# Créer la base SQL Server réutilisable avec les deux tables nettoyées
persist_clean_tables(ChargesTelephoniques, ChargesImpression)

[LOAD] Création de la base nettoyée et persistance des tables...
  ✓ Base 'Yazaki_Clean' prête avec 2 table(s) nettoyée(s)
  ✓ ChargesTelephoniques: (4945, 9)
  ✓ ChargesImpression   : (9945, 9)

## Load

In [9]:
# import de la fonction de chargement
from etl.load import load_all

In [10]:
# Chargement des données dans le Data Warehouse
load_all(ChargesTelephoniques, ChargesImpression)

================================================================================
[PIPELINE] LOAD - Chargement des données dans DW_Yazaki
================================================================================

[LOAD] Suppression des données existantes...
  ✓ Tables vidées
[LOAD] Chargement Dim_Departement...
  ✓ 16 département(s) chargé(s)
[LOAD] Chargement Dim_Role...
  ✓ 11 rôle(s) chargé(s)
[LOAD] Chargement Dim_Employee...
  ✓ 131 employé(s) chargé(s)
[LOAD] (Re)chargement Dim_Temps (DateID = 1..n)...
  ✓ Dim_Temps chargée: 1247 date(s) (2023-01-01 → 2026-05-31)
[LOAD] Chargement Dim_Impression...
  ✓ 4 type(s) d'impression chargé(s)
[LOAD] Chargement Fact_Telephone...
  ✓ 4945 ligne(s) chargée(s) dans Fact_Telephone
[LOAD] Chargement Fact_Impression...
  ✓ 9945 ligne(s) chargée(s) dans Fact_Impression

================================================================================
[SUCCÈS] Chargement terminé avec succès dans DW_Yazaki !
================================================================================