## Extract

In [1]:
# import des fonctions d'extraction et transformation
import importlib
import sys
if 'etl.transform' in sys.modules:
    del sys.modules['etl.transform']
if 'etl.extract' in sys.modules:
    del sys.modules['etl.extract']
    
from etl.extract import extract_charges_telephoniques, extract_charges_impression
from etl.transform import transform_charges_telephoniques, transform_charges_impression

In [2]:
# Extraction + Transformation des données en une seule étape
ChargesTelephoniques = extract_charges_telephoniques()
ChargesImpression = extract_charges_impression()
ChargesTelephoniques = transform_charges_telephoniques(ChargesTelephoniques)
ChargesImpression = transform_charges_impression(ChargesImpression)

print(f"ChargesTelephoniques : {ChargesTelephoniques.shape}")
print(f"ChargesImpression   : {ChargesImpression.shape}")

[INFO] Validation dates ChargesTelephoniques - colonne 'DateOperation'...
  ✓ Toutes les dates valides (5767 lignes)
[INFO] Normalisation NomDepartement (ChargesTelephoniques)...
  ⚠️  47 département(s) invalide(s) détecté(s)
  ✓ 47 ligne(s) imputée(s) via CodeEmployee
[INFO] Uniformisation NomDepartement (le plus récurrent par CodeEmployee)...
  ✓ 180 CodeEmployee(s) ont un NomDepartement unique
[INFO] Normalisation CodeEmployee (format: YAZ+nombre ou INCONNU)...
  ✓ CodeEmployee reformatés
[INFO] Propagation NomRole et NumeroTelephone (dernier jour du mois → tous les jours du mois)...
  ✓ 5767 combinaison(s) traité(e)s
[INFO] Suppression doublons ChargesTelephoniques...
  ✓ Aucun doublon détecté
[INFO] Réassignation IDs et tri ChargesTelephoniques...
  ✓ 5767 lignes conservées, IDs réassignés (1-5767)
    - 5767 lignes valides
    - 0 lignes avec date invalide
[INFO] Validation dates ChargesImpression - colonne 'DateImpression'...
  ✓ Toutes les dates valides (15232 lignes)
[INFO] Normalisation NomDepartement (ChargesImpression)...
  ⚠️  165 département(s) invalide(s) → 'INCONNU'
[INFO] Validation TypeImpression...
  ✓ Tous les types impression valides
[INFO] Extraction CouleurImpression et FormatPapier...
  ✓ Extraction complète
[INFO] Correction CoutUnitaire...
  ✓ CoutUnitaire corrigés
[INFO] Correction NbPages (positif, NA → 0)...
  ✓ NbPages corrigés
[INFO] Réassignation IDs et tri ChargesImpression...
  ✓ 15232 lignes conservées, IDs réassignés (1-15232)
    - 15232 lignes valides
    - 0 lignes avec date invalide
ChargesTelephoniques : (5767, 10)
ChargesImpression   : (15232, 10)

In [3]:
# Affichage des premières lignes du DataFrame ChargesTelephoniques
ChargesTelephoniques.head()

,TelephoniqueID,NomDepartement,CodeDepartement,DateOperation,NomRole,CodeRole,CodeEmployee,NumeroTelephone,ForfaitTND,DateValid
0,1,PRODUCTION A,PROD-A,2022-01-01,MANAGER,MGR,YAZ001,20112233,100,True
1,2,TD,TD,2022-01-01,TECHNICIEN,TECH,YAZ095,50656677,25,True
2,3,TD,TD,2022-01-01,TECHNICIEN,TECH,YAZ094,20545566,25,True
3,4,TD,TD,2022-01-01,TECHNICIEN,TECH,YAZ093,90434455,25,True
4,5,TD,TD,2022-01-01,TECHNICIEN,TECH,YAZ092,50323344,25,True

In [4]:
# affichages des premières lignes du DataFrame ChargesImpression
ChargesImpression.head()

,ImpressionID,NomDepartement,CodeDepartement,DateImpression,TypeImpression,NbPages,CoutUnitaire,FormatPapier,CouleurImpression,DateValid
0,1,COSEE,COSEE,2022-01-01,A4-NB,43,0.026,A4,NOIR ET BLANC,True
1,2,PRODUCTION B,PROD-B,2022-01-01,A4-NB,39,0.026,A4,NOIR ET BLANC,True
2,3,PRODUCTION B,PROD-B,2022-01-01,A4-NB,33,0.026,A4,NOIR ET BLANC,True
3,4,OLS,OLS,2022-01-01,A4-NB,47,0.026,A4,NOIR ET BLANC,True
4,5,OLS,OLS,2022-01-01,A4-COULEUR,4,0.156,A4,COULEUR,True

## Transform

In [5]:
# Affichage des données transformées - ChargesTelephoniques

In [6]:
print(f"ChargesTelephoniques apres transformation : {ChargesTelephoniques.shape}")
ChargesTelephoniques.head()

ChargesTelephoniques apres transformation : (5767, 10)

,TelephoniqueID,NomDepartement,CodeDepartement,DateOperation,NomRole,CodeRole,CodeEmployee,NumeroTelephone,ForfaitTND,DateValid
0,1,PRODUCTION A,PROD-A,2022-01-01,MANAGER,MGR,YAZ001,20112233,100,True
1,2,TD,TD,2022-01-01,TECHNICIEN,TECH,YAZ095,50656677,25,True
2,3,TD,TD,2022-01-01,TECHNICIEN,TECH,YAZ094,20545566,25,True
3,4,TD,TD,2022-01-01,TECHNICIEN,TECH,YAZ093,90434455,25,True
4,5,TD,TD,2022-01-01,TECHNICIEN,TECH,YAZ092,50323344,25,True

In [7]:
print(f"ChargesImpression apres transformation : {ChargesImpression.shape}")
ChargesImpression.head()

ChargesImpression apres transformation : (15232, 10)

,ImpressionID,NomDepartement,CodeDepartement,DateImpression,TypeImpression,NbPages,CoutUnitaire,FormatPapier,CouleurImpression,DateValid
0,1,COSEE,COSEE,2022-01-01,A4-NB,43,0.026,A4,NOIR ET BLANC,True
1,2,PRODUCTION B,PROD-B,2022-01-01,A4-NB,39,0.026,A4,NOIR ET BLANC,True
2,3,PRODUCTION B,PROD-B,2022-01-01,A4-NB,33,0.026,A4,NOIR ET BLANC,True
3,4,OLS,OLS,2022-01-01,A4-NB,47,0.026,A4,NOIR ET BLANC,True
4,5,OLS,OLS,2022-01-01,A4-COULEUR,4,0.156,A4,COULEUR,True

## Load

In [8]:
# import de la fonction de chargement
from etl.load import load_all

In [9]:
# Chargement des données dans le Data Warehouse
load_all(ChargesTelephoniques, ChargesImpression)

================================================================================
[PIPELINE] LOAD - Chargement des données dans DW_Yazaki
================================================================================

[LOAD] Suppression des données existantes...
  ✓ Tables vidées (Dim_Temps incluse)
[LOAD] Chargement Dim_Departement...
  ✓ 17 département(s) chargé(s)
[LOAD] Chargement Dim_Role...
  ✓ 11 rôle(s) chargé(s)
[LOAD] Chargement Dim_Employee...
  ✓ 131 employé(s) chargé(s)
[LOAD] (Re)chargement Dim_Temps (DateID = 1..n)...
  ✓ Dim_Temps chargée: 1458 date(s) (2022-01-01 → 2025-12-28)
[LOAD] Chargement Dim_Impression...
  ✓ 4 type(s) d'impression chargé(s)
[LOAD] Chargement Fact_Telephone...
  ✓ 5767 ligne(s) chargée(s) dans Fact_Telephone
[LOAD] Chargement Fact_Impression...
  ✓ 15232 ligne(s) chargée(s) dans Fact_Impression

================================================================================
[SUCCÈS] Chargement terminé avec succès dans DW_Yazaki !
================================================================================

In [11]:
ChargesTelephoniques

,TelephoniqueID,NomDepartement,CodeDepartement,DateOperation,NomRole,CodeRole,CodeEmployee,NumeroTelephone,ForfaitTND,DateValid
0,1,PRODUCTION A,PROD-A,2022-01-01,MANAGER,MGR,YAZ001,20112233,100,True
1,2,TD,TD,2022-01-01,TECHNICIEN,TECH,YAZ095,50656677,25,True
2,3,TD,TD,2022-01-01,TECHNICIEN,TECH,YAZ094,20545566,25,True
3,4,TD,TD,2022-01-01,TECHNICIEN,TECH,YAZ093,90434455,25,True
4,5,TD,TD,2022-01-01,TECHNICIEN,TECH,YAZ092,50323344,25,True
...,...,...,...,...,...,...,...,...,...,...
5762,5763,ENGENIERIE,ENG,2025-12-01,TECHNICIEN,TECH,YAZ074,50243344,25,True
5763,5764,ENGENIERIE,ENG,2025-12-01,TECHNICIEN,TECH,YAZ075,90354455,25,True
5764,5765,ENGENIERIE,ENG,2025-12-01,TECHNICIEN,TECH,YAZ076,20465566,25,True
5765,5766,ENGENIERIE,ENG,2025-12-01,SPECIALISTE,SP,YAZ068,50586677,40,True
5766,5767,OLS,OLS,2025-12-01,MANAGER,MGR,YAZ113,50536475,100,True