# Test Extract & Transform

In [1]:
from etl.extract import extract_charges_telephoniques, extract_charges_impression
from etl.transform import transform_charges_telephoniques, transform_charges_impression

## Extract

In [2]:
ChargesTelephoniques = extract_charges_telephoniques()
ChargesImpression = extract_charges_impression()

print(f"ChargesTelephoniques : {ChargesTelephoniques.shape}")
print(f"ChargesImpression   : {ChargesImpression.shape}")

ChargesTelephoniques : (6240, 10)
ChargesImpression   : (16007, 10)

c:\Projet fin d'etude\ETL-Yazaki\etl\extract.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  ChargesTelephoniques = pd.read_sql("SELECT * FROM ChargesTelephoniques", conn)
c:\Projet fin d'etude\ETL-Yazaki\etl\extract.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  ChargesImpression = pd.read_sql("SELECT * FROM ChargesImpression", conn)

In [3]:
ChargesTelephoniques.head()

,TelephoniqueID,CodeDepartement,NomDepartement,NomResponsable,DateOperation,NomRole,CodeEmployee,NumeroTel,ForfaitTND,ChargesVariables
0,1,PROD-A,Production A,Ahmed Ben Salem,2022-01,Manager,YAZ001,20112233,100.0,0.0
1,2,PROD-A,Production A,Ahmed Ben Salem,2022-01,Specialiste,YAZ002,50223344,40.0,0.0
2,3,PROD-A,Production A,Ahmed Ben Salem,2022-01,Technicien,YAZ003,90334455,20.0,0.0
3,4,PROD-A,Production A,Ahmed Ben Salem,2022-01,Technicien,YAZ004,20445566,20.0,0.0
4,5,PROD-B,Production B,Mehdi Karray,2022-01,Manager,YAZ005,50556677,100.0,0.0

In [4]:
ChargesImpression.head()

,ImpressionID,NomDepartement,CodeDepartement,NomResponsable,DateImpression,CouleurImpression,CodeDetailImpression,NbPages,Format,CoutUnitaire
0,1,Achat,ACH,Jamel Baccouche,2022-01-01,A3 - Noir et Blanc,A3-NB,41,A3,0.048
1,2,Cosee,COSEE,Ridha Jendoubi,2022-01-01,A4 - Noir et Blanc,A4-NB,11,A4,0.024
2,3,EHS,EHS,Chokri Gharbi,2022-01-01,A4 - Noir et Blanc,A4-NB,50,A4,0.024
3,4,Engineering,ENG,Salah Mansour,2022-01-01,A3 - Couleur,A3-COULEUR,29,A3,0.986
4,5,Engineering,ENG,Salah Mansour,2022-01-01,A4 - Noir et Blanc,A4-NB,3,A4,0.024

## Transform

In [5]:
ChargesTelephoniques = transform_charges_telephoniques(ChargesTelephoniques)

print(f"ChargesTelephoniques apr\u00e8s transformation : {ChargesTelephoniques.shape}")
ChargesTelephoniques.head()

ChargesTelephoniques après transformation : (6240, 11)

,TelephoniqueID,CodeDepartement,NomDepartement,NomResponsable,DateOperation,CodeRole,NomRole,CodeEmployee,NumeroTel,ForfaitTND,ChargesVariables
0,1,PROD-A,Production A,Ahmed Ben Salem,2022-01-01,MGR,Manager,YAZ001,20112233,100.0,0.0
1,2,PROD-A,Production A,Ahmed Ben Salem,2022-01-01,SP,Specialiste,YAZ002,50223344,40.0,0.0
2,3,PROD-A,Production A,Ahmed Ben Salem,2022-01-01,TECH,Technicien,YAZ003,90334455,25.0,0.0
3,4,PROD-A,Production A,Ahmed Ben Salem,2022-01-01,TECH,Technicien,YAZ004,20445566,25.0,0.0
4,5,PROD-B,Production B,Mehdi Karray,2022-01-01,MGR,Manager,YAZ005,50556677,100.0,0.0

In [6]:
ChargesImpression = transform_charges_impression(ChargesImpression)

print(f"ChargesImpression apr\u00e8s transformation : {ChargesImpression.shape}")
ChargesImpression.head()

ChargesImpression après transformation : (16007, 10)

,ImpressionID,NomDepartement,CodeDepartement,NomResponsable,DateImpression,CouleurImpression,CodeDetailImpression,NbPages,Format,CoutUnitaire
0,1,Achat,ACH,Jamel Baccouche,2022-01-01,Noir et Blanc,A3-NB,41,A3,0.048
1,2,Cosee,COSEE,Ridha Jendoubi,2022-01-01,Noir et Blanc,A4-NB,11,A4,0.024
2,3,EHS,EHS,Chokri Gharbi,2022-01-01,Noir et Blanc,A4-NB,50,A4,0.024
3,4,Engineering,ENG,Salah Mansour,2022-01-01,Couleur,A3-COULEUR,29,A3,0.986
4,5,Engineering,ENG,Salah Mansour,2022-01-01,Noir et Blanc,A4-NB,3,A4,0.024

## V\u00e9rifications

In [7]:
print("Valeurs manquantes - ChargesTelephoniques :")
print(ChargesTelephoniques.isnull().sum())
print("\nValeurs manquantes - ChargesImpression :")
print(ChargesImpression.isnull().sum())

Valeurs manquantes - ChargesTelephoniques :
TelephoniqueID      0
CodeDepartement     0
NomDepartement      0
NomResponsable      0
DateOperation       0
CodeRole            0
NomRole             0
CodeEmployee        0
NumeroTel           0
ForfaitTND          0
ChargesVariables    0
dtype: int64

Valeurs manquantes - ChargesImpression :
ImpressionID            0
NomDepartement          0
CodeDepartement         0
NomResponsable          0
DateImpression          0
CouleurImpression       0
CodeDetailImpression    0
NbPages                 0
Format                  0
CoutUnitaire            0
dtype: int64

In [8]:
print("Types - ChargesTelephoniques :")
print(ChargesTelephoniques.dtypes)
print("\nTypes - ChargesImpression :")
print(ChargesImpression.dtypes)

Types - ChargesTelephoniques :
TelephoniqueID               int64
CodeDepartement     string[python]
NomDepartement      string[python]
NomResponsable      string[python]
DateOperation       datetime64[ns]
CodeRole            string[python]
NomRole             string[python]
CodeEmployee        string[python]
NumeroTel           string[python]
ForfaitTND                 float64
ChargesVariables           float64
dtype: object

Types - ChargesImpression :
ImpressionID                     int64
NomDepartement          string[python]
CodeDepartement         string[python]
NomResponsable          string[python]
DateImpression          datetime64[ns]
CouleurImpression       string[python]
CodeDetailImpression    string[python]
NbPages                          int64
Format                  string[python]
CoutUnitaire                   float64
dtype: object

## Load

In [9]:
from etl.load import load_all

load_all(ChargesTelephoniques, ChargesImpression)

[LOAD] Tables videes (Dim_Temps conservee)
[LOAD] 16 lignes chargees dans Dim_Departement
[LOAD] 130 lignes chargees dans Dim_Employee
[LOAD] 10 lignes chargees dans Dim_Role
[LOAD] 4 lignes chargees dans Dim_Impression
[LOAD] 6240 lignes chargees dans Fact_Telephone
[LOAD] 16007 lignes chargees dans Fact_Impression
[LOAD] Chargement termine avec succes

## Vérification du chargement

In [10]:
import pandas as pd
from etl.config import get_dw_engine

engine = get_dw_engine()

tables = ['Dim_Departement', 'Dim_Employee', 'Dim_Role', 'Dim_Impression',
          'Dim_Temps', 'Fact_Telephone', 'Fact_Impression']

for table in tables:
    df = pd.read_sql(f"SELECT COUNT(*) AS nb FROM {table}", engine)
    print(f"{table:20s} : {df['nb'].iloc[0]} lignes")

Dim_Departement      : 16 lignes
Dim_Employee         : 130 lignes
Dim_Role             : 10 lignes
Dim_Impression       : 4 lignes
Dim_Temps            : 1461 lignes
Fact_Telephone       : 6240 lignes
Fact_Impression      : 16007 lignes

In [11]:
pd.read_sql("SELECT TOP 5 * FROM Dim_Departement", engine)

,DepartementID,CodeDepartement,NomDepartement,DescriptionDept,NomResponsable
0,1,PROD-A,Production A,Ligne de production P1 et P2,Ahmed Ben Salem
1,2,PROD-B,Production B,Ligne de production P3,Mehdi Karray
2,3,DIR,Direction,Administration générale,Hedi Ammar
3,4,IT,IT,Support informatique et systèmes,Slim Touati
4,5,FIN,Finance,Gestion financière et comptabilité,Omar Cherif

In [12]:
pd.read_sql("SELECT TOP 5 * FROM Dim_Employee", engine)

   EmployeeID CodeEmployee NumeroEmployee
0           1       YAZ001       20112233
1           2       YAZ002       50223344
2           3       YAZ003       90334455
3           4       YAZ004       20445566
4           5       YAZ005       50556677

In [13]:
pd.read_sql("SELECT TOP 5 * FROM Dim_Role", engine)

,RoleID,CodeRole,NomRole,NiveauHierarchique,DescriptionRole
0,1,MGR,Manager,3,"Responsable d'équipe ou de service, chargé de ..."
1,2,SP,Specialiste,9,"Employé senior ou spécialiste technique, respo..."
2,3,TECH,Technicien,10,Employé technique ou administratif assurant l'...
3,4,SUP,Superviseur,8,Encadrant intermédiaire supervisant les activi...
4,5,LL,Line Leader,11,"Responsable d'une ligne de production, chargé ..."

In [14]:
pd.read_sql("SELECT TOP 5 * FROM Dim_Impression", engine)

   ImpressionID CodeImpression CouleurImpression FormatPapier
0             1          A3-NB     Noir et Blanc           A3
1             2          A4-NB     Noir et Blanc           A4
2             3     A3-COULEUR           Couleur           A3
3             4     A4-COULEUR           Couleur           A4

In [15]:
pd.read_sql("SELECT TOP 5 * FROM Fact_Telephone", engine)

,ID,DepartementID,EmployeeID,RoleID,DateID,ForfaitTND,ChargesVariables
0,1,1,1,1,20220101,100.0,0.0
1,2,1,2,2,20220101,40.0,0.0
2,3,1,3,3,20220101,25.0,0.0
3,4,1,4,3,20220101,25.0,0.0
4,5,2,5,1,20220101,100.0,0.0

In [16]:
pd.read_sql("SELECT TOP 5 * FROM Fact_Impression", engine)

   ID  DepartementID    DateID  ImpressionID  NbPages  CoutUnitaire
0   1              8  20220101             1       41         0.048
1   2              9  20220101             2       11         0.024
2   3              6  20220101             2       50         0.024
3   4             10  20220101             3       29         0.986
4   5             10  20220101             2        3         0.024

In [17]:
# Check actual columns in Dim_Employee table
import pandas as pd
from etl.config import get_dw_engine

engine = get_dw_engine()
schema_query = """
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Dim_Employee'
ORDER BY ORDINAL_POSITION
"""
pd.read_sql(schema_query, engine)

      COLUMN_NAME DATA_TYPE  CHARACTER_MAXIMUM_LENGTH
0      EmployeeID       int                       NaN
1    CodeEmployee  nvarchar                      50.0
2  NumeroEmployee  nvarchar                      50.0

In [ ]:
# Check actual columns in Dim_Employee table
import pandas as pd
from etl.config import get_dw_engine

engine = get_dw_engine()
schema_query = """
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Dim_Employee'
ORDER BY ORDINAL_POSITION
"""
pd.read_sql(schema_query, engine)